export const initialSports = [
  "Gymnastics",
  "Football",
  "Handball",
  "Hockey",
  "Judo",
  "Kabaddi",
  "Taekwondo",
  "Kayaking & Canoeing",
  "Archery",
  "Athletics",
  "Swimming",
  "Badminton",
  "Basketball",
  "Boxing",
  "Kho-Kho",
  "Lawn Tennis",
  "Rifle",
  "Rowing",
  "Volleyball",
  "Triathlon",
  "Table Tennis",
  "Wushu",
  "Fencing",
  "Rugby",
  "Wrestling",
  "Weightlifting",
  "Cycling",
  "Pentathlon",
  "Netball",
  "Squash Rackets",
  "Rollball",
  "Sepak Takraw",
  "Atyapatya",
  "Carrom",
  "Soft Tennis",
  "Kurash",
  "Tenni-Koit",
  "Mallakhamb",
  "Softball",
  "Amateur Gymnastics",
  "Tug of War",
  "Bodybuilding",
  "Ball Badminton",
  "Thang-Ta"
];
export function sortSports<T extends { title: string; order?: number }>(rows: T[]): T[] {
  return [...rows].sort((a,b) => (a.order ?? 0) - (b.order ?? 0) || a.title.localeCompare(b.title));
}
